# Generated by Django 4.2.7 on 2023-11-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_name', models.CharField(blank=True, max_length=150, null=True)),
                ('specialization', models.CharField(max_length=150)),
                ('contact_details', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('contact_details', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('result_value', models.CharField(max_length=150)),
                ('unit', models.CharField(max_length=150)),
                ('interpretation', models.CharField(max_length=100)),
                ('result_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sample_type', models.CharField(max_length=150)),
                ('collection_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
    ]
